// <auto-generated />
namespace Sample.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Rebase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rebase));
        
        string IMigrationMetadata.Id
        {
            get { return "201406151623032_Rebase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
